version: "3.8"

services:
  app:
    image: ainee-extractor:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3011:3011"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
