/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export { CustomOpenApi } from './CustomOpenApi';

export { ApiError } from './core/ApiError';
export { BaseHttpRequest } from './core/BaseHttpRequest';
export { CancelablePromise, CancelError } from './core/CancelablePromise';
export { OpenAPI } from './core/OpenAPI';
export type { OpenAPIConfig } from './core/OpenAPI';

export { AnnotationAction } from './models/AnnotationAction';
export type { AnnotationResponse } from './models/AnnotationResponse';
export type { AnnotationsResponse } from './models/AnnotationsResponse';
export type { AvailableContentResponse } from './models/AvailableContentResponse';
export type { BatchCreatedItemReponse } from './models/BatchCreatedItemReponse';
export type { Body_create_by_url_api_content_create_by_url_post } from './models/Body_create_by_url_api_content_create_by_url_post';
export type { Body_create_upload_and_pends_api_content_create_upload_and_pend_post } from './models/Body_create_upload_and_pends_api_content_create_upload_and_pend_post';
export type { Body_generate_flashcards_api_ainee_web_flashcards_generate_post } from './models/Body_generate_flashcards_api_ainee_web_flashcards_generate_post';
export type { Body_stream_agent_chat_api_chat_stream_agent_chat_post } from './models/Body_stream_agent_chat_api_chat_stream_agent_chat_post';
export type { Body_stream_rag_chat_api_chat_stream_rag_chat_post } from './models/Body_stream_rag_chat_api_chat_stream_rag_chat_post';
export type { Body_upload_and_pends_api_content_upload_and_pend_post } from './models/Body_upload_and_pends_api_content_upload_and_pend_post';
export type { Body_upload_avatar_api_user_upload_avatar_post } from './models/Body_upload_avatar_api_user_upload_avatar_post';
export type { Body_upload_file_with_params_api_ainee_web_cornell_notes_generate_post } from './models/Body_upload_file_with_params_api_ainee_web_cornell_notes_generate_post';
export type { Body_welcome_follow_up_question_api_chat_welcome_follow_up_question_get } from './models/Body_welcome_follow_up_question_api_chat_welcome_follow_up_question_get';
export { ChatStartType } from './models/ChatStartType';
export type { CommonResponse_AnnotationResponse_ } from './models/CommonResponse_AnnotationResponse_';
export type { CommonResponse_AnnotationsResponse_ } from './models/CommonResponse_AnnotationsResponse_';
export type { CommonResponse_bool_ } from './models/CommonResponse_bool_';
export type { CommonResponse_ContentResponse_ } from './models/CommonResponse_ContentResponse_';
export type { CommonResponse_dict_ } from './models/CommonResponse_dict_';
export type { CommonResponse_FlashcardGenerationResult_ } from './models/CommonResponse_FlashcardGenerationResult_';
export type { CommonResponse_KBProcessingStatusResponse_ } from './models/CommonResponse_KBProcessingStatusResponse_';
export type { CommonResponse_ManageAnnotationResponse_ } from './models/CommonResponse_ManageAnnotationResponse_';
export type { CommonResponse_str_ } from './models/CommonResponse_str_';
export type { CommonResponse_TeacherThankYouNoteResponse_ } from './models/CommonResponse_TeacherThankYouNoteResponse_';
export type { CommonResponse_Union_bool__NoneType__ } from './models/CommonResponse_Union_bool__NoneType__';
export type { CommonResponse_Union_ContentResponse__NoneType__ } from './models/CommonResponse_Union_ContentResponse__NoneType__';
export type { CommonResponse_Union_CornellNotesResult__NoneType__ } from './models/CommonResponse_Union_CornellNotesResult__NoneType__';
export type { CommonResponse_Union_dict__NoneType__ } from './models/CommonResponse_Union_dict__NoneType__';
export type { CommonResponse_Union_KnowledgeBaseListResponse__NoneType__ } from './models/CommonResponse_Union_KnowledgeBaseListResponse__NoneType__';
export type { CommonResponse_Union_KnowledgeBaseResponse__NoneType__ } from './models/CommonResponse_Union_KnowledgeBaseResponse__NoneType__';
export type { CommonResponse_Union_List_AvailableContentResponse___NoneType__ } from './models/CommonResponse_Union_List_AvailableContentResponse___NoneType__';
export type { CommonResponse_Union_List_BatchCreatedItemReponse___NoneType__ } from './models/CommonResponse_Union_List_BatchCreatedItemReponse___NoneType__';
export type { CommonResponse_Union_List_ContentResponse___NoneType__ } from './models/CommonResponse_Union_List_ContentResponse___NoneType__';
export type { CommonResponse_Union_LoginResponse__NoneType__ } from './models/CommonResponse_Union_LoginResponse__NoneType__';
export type { CommonResponse_Union_str__NoneType__ } from './models/CommonResponse_Union_str__NoneType__';
export type { CommonResponse_Union_ThankYouNoteResponse__NoneType__ } from './models/CommonResponse_Union_ThankYouNoteResponse__NoneType__';
export type { CommonResponse_Union_YouTubeTranscriptionResponse__NoneType__ } from './models/CommonResponse_Union_YouTubeTranscriptionResponse__NoneType__';
export type { CommonResponse_UserContentsData_ } from './models/CommonResponse_UserContentsData_';
export type { CommonResponse_UserInfoResponse_ } from './models/CommonResponse_UserInfoResponse_';
export type { CommonResponse_WelcomeFollowUpQuestionResponse_ } from './models/CommonResponse_WelcomeFollowUpQuestionResponse_';
export { ContentMediaType } from './models/ContentMediaType';
export type { ContentResponse } from './models/ContentResponse';
export type { ContentStats } from './models/ContentStats';
export type { ContentToKnowledgeBaseRequest } from './models/ContentToKnowledgeBaseRequest';
export type { CopyContentsRequest } from './models/CopyContentsRequest';
export type { CornellNote } from './models/CornellNote';
export type { CornellNotePage } from './models/CornellNotePage';
export type { CornellNotesResult } from './models/CornellNotesResult';
export type { CreateAnnotationRequest } from './models/CreateAnnotationRequest';
export type { CreateContentRequest } from './models/CreateContentRequest';
export type { CreateKnowledgeBaseRequest } from './models/CreateKnowledgeBaseRequest';
export type { EditContentRequest } from './models/EditContentRequest';
export type { Flashcard } from './models/Flashcard';
export type { FlashcardGenerationResult } from './models/FlashcardGenerationResult';
export type { FlashcardMetadata } from './models/FlashcardMetadata';
export type { HTTPValidationError } from './models/HTTPValidationError';
export { KBProcessingStatus } from './models/KBProcessingStatus';
export type { KBProcessingStatusResponse } from './models/KBProcessingStatusResponse';
export type { KnowledgeBaseInfo } from './models/KnowledgeBaseInfo';
export type { KnowledgeBaseListResponse } from './models/KnowledgeBaseListResponse';
export type { KnowledgeBaseResponse } from './models/KnowledgeBaseResponse';
export { KnowledgeBaseType } from './models/KnowledgeBaseType';
export { KnowledgeBaseVisibility } from './models/KnowledgeBaseVisibility';
export type { LoginRequest } from './models/LoginRequest';
export type { LoginResponse } from './models/LoginResponse';
export type { ManageAnnotationRequest } from './models/ManageAnnotationRequest';
export type { ManageAnnotationResponse } from './models/ManageAnnotationResponse';
export type { MediaItem } from './models/MediaItem';
export { ProcessingStatus } from './models/ProcessingStatus';
export { ResponseCode } from './models/ResponseCode';
export type { RetryContentRequest } from './models/RetryContentRequest';
export type { SubtitleSegment } from './models/SubtitleSegment';
export type { TeacherThankYouNoteRequest } from './models/TeacherThankYouNoteRequest';
export type { TeacherThankYouNoteResponse } from './models/TeacherThankYouNoteResponse';
export type { ThankYouNoteRequest } from './models/ThankYouNoteRequest';
export type { ThankYouNoteResponse } from './models/ThankYouNoteResponse';
export type { UpdateFCMTokenRequest } from './models/UpdateFCMTokenRequest';
export type { UpdateKnowledgeBaseRequest } from './models/UpdateKnowledgeBaseRequest';
export type { UserContentsData } from './models/UserContentsData';
export type { UserInfoResponse } from './models/UserInfoResponse';
export type { UserUpdateRequest } from './models/UserUpdateRequest';
export type { ValidationError } from './models/ValidationError';
export type { WelcomeFollowUpQuestionResponse } from './models/WelcomeFollowUpQuestionResponse';
export type { YouTubeTranscriptionRequest } from './models/YouTubeTranscriptionRequest';
export type { YouTubeTranscriptionResponse } from './models/YouTubeTranscriptionResponse';

export { AineeWebService } from './services/AineeWebService';
export { AnnotationService } from './services/AnnotationService';
export { ChatService } from './services/ChatService';
export { ContentService } from './services/ContentService';
export { KnowledgeBaseService } from './services/KnowledgeBaseService';
export { UserService } from './services/UserService';
