version: "3.8"

services:
  app:
    image: ainee-web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3019:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
